services:
  app:
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - redis
    env_file:
      - .env.prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  redis:
    image: redis:8
    restart: always
    ports:
      - '6379:6379'

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus-prod.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - '7070:3000'
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data: