spring:
  profiles:
    active: local
  application:
    name: typing-practice-be

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


dotenv:
  path: .env.${spring.profiles.active}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

google:
  token-uri: https://oauth2.googleapis.com/token

quote:
  difficulty:
    cold-start-k: 20
  similarity-threshold:
    korean: 0.5
    english: 0.5

adaptive-serving:
  beta: 15
  sigma-obs: 4 #10
  perf-coefficient: 1.5
  sigma-process: 1 #2
  surprise-threshold: 2
  default-mu: 50
  default-sigma: 15